### ISSUE TITLE
For you & Search

### ISSUE THREAD

**Issue by shyalan** [GDSC-La-Trobe-University/glider-bus-tracking-website#5]
- [ ] Remove the Map in Search (There shouldn't be a map there)
- [ ] Swap the For You with Search, Meaning: Whatever is in ForYou Page is supposed to be in Search Page and in %%.
Search should look like this:
![image](https://github.com/user-attachments/assets/ff0b7d4c-297f-41dd-b47f-62a240c11020)

ForYou should look like this:
![image](https://github.com/user-attachments/assets/118477c3-0e11-4582-ac82-01680c1679bf)
And if there is none stared, it should show this:
![image](https://github.com/user-attachments/assets/e00edbed-e52c-4a10-b299-b54f0cbcfa95)
Here the code with the similar styles for the above one:
`<div className="mt-36 flex flex-col items-center justify-center h-full text-gray-500">
            <p>Click to add Favourites</p>
            <button
              className="mt-1 px-3 py-1 border border-gray-500 rounded-md bg-transparent text-gray-500 flex items-center text-sm"
              onClick={handleSearchClick}
            >
              <FontAwesomeIcon icon={faPlus} className="mr-1" />
              Add
            </button>
          </div>`

**Comment by L2-Izana** [comment]
https://github.com/gdsclatrobe/glider-bus-tracking-website/tree/dev-search-foryou

**Comment by L2-Izana** [comment]
https://github.com/gdsclatrobe/glider-bus-tracking-website/tree/dev-search-foryou
