### ISSUE TITLE
For You Page - Bug

### ISSUE THREAD

**Issue by shyalan** [GDSC-La-Trobe-University/glider-bus-tracking-website#6]
In the For You Page, When I try to unstar something, It doesn't get un-stared.
![image](https://github.com/user-attachments/assets/2e9e05eb-6b3e-4491-aa13-df2cdf93a4e3)
When I click the star, It should remove that item from the For you (Basically Un-star it)

**Comment by L2-Izana** [comment]
https://github.com/gdsclatrobe/glider-bus-tracking-website/tree/dev-search-foryou
