### ISSUE TITLE
MapView Code Deletion + Mapping Updates

### ISSUE THREAD

**Issue by shyalan** [GDSC-La-Trobe-University/glider-bus-tracking-website#7]
- [x] Create a new branch called 'dev-map-updates-v1.2'
- [x] Remove all code for the Map Page (let it return an empty MapviewPage)
- [x] Then redo the map to be within the frame (above the navbar but 100vh)
- [x] In the Data file, mark those locations on the map
- [x] Commit & Push to branch
- [x] Create a merge request to main

**Comment by L2-Izana** [comment]
https://github.com/gdsclatrobe/glider-bus-tracking-website/issues/7
